### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by chrisjlee** [hustcc/jest-date-mock#10]
Is this ISC license or MIT licensed? I don't see i LICENSE file.

**Comment by hustcc** [comment]
MIT.

sorry for difference between `package.json` and `readme.md`.

**Comment by hustcc** [comment]
There are no difference in usage between mit and isc.

**Comment by hustcc** [comment]
https://github.com/hustcc/jest-date-mock/commit/506281ad4fa977438a27ad23f6fdc4abfc403b73 Change to MIT.

**Comment by chrisjlee** [comment]
Thanks!
