### ISSUE TITLE
Better method names?

### ISSUE THREAD

**Issue by FezVrasta** [hustcc/jest-date-mock#12]
Hi, your library is very useful, it saved me quite few times already.

But the method names are not intuitive at all...

`advanceTo` makes the user think you can use it only to set a date in the future, but you can actually "advance" to a past date? It's not very intuitive. Maybe `setTo` would be more user friendly?

`clear` makes the user think you can use it to "clear" the current mocked date and get back to the original one, but it actually destroys the mock utility all together... Maybe `unmock` would be easier to understand?

Thanks for the help!

**Comment by hustcc** [comment]
yeah, advance means set a date in the future, but relative to timestamp = 0.

`unmock` is very nice, but will cause IDE yellow warning line about spell 😂.

if change to setTo, advanceBy, unmock. There will be 3 api completely, but now just 2.5 😂

Change names will lead to incompatibility.

I am very entangled in whether or not to change their names.

**Comment by kipanshi** [comment]
Thanks for this library.

You can keep existing method names as aliases for backward compatibility and introduce the new ones.
 I like explicit names:
`advanceTo  ->  setDate`
`advanceBy -> incrementDate`
`clear  ->  clearDateMock`

**Comment by hustcc** [comment]
i think the function names are good enough for using.

may be will change clear to unmock.
