### ISSUE TITLE
advanceBy as first function call result in nowDate being NaN

### ISSUE THREAD

**Issue by dotnetCarpenter** [hustcc/jest-date-mock#15]
## Steps:

1.
```js
export default function getTimeDuration () {
  const startTimestamp = Date.now()

  return () => {
    return Date.now() - startTimestamp
  }
}
```

2.
```js
test.only('duration used by PayloadTiming', () => {
    const timer = getTimeDuration()

    jestDateMock.advanceBy(10)
    expect(timer()).toBe(10)
    jestDateMock.clear()
  })
```

**Comment by hustcc** [comment]
May not be a bug, or there has no perfact way to solve it.

I think you can refer to https://github.com/hustcc/jest-date-mock/blob/master/__tests__/index.js#L8-L13

**Comment by dotnetCarpenter** [comment]
Why can we not set the `DEFAULT` value to `0` instead of `undefined`?

**Comment by dotnetCarpenter** [comment]
I see that the `clear()` test fails if I do it, but I'm unsure as to why. Does `Date.now()` revert to the original `Date.now()` when `nowDate` is `undefined`?

**Comment by hustcc** [comment]
When undefined means 'not mock date', else mock date with the number as timestamp.
