### ISSUE TITLE
Date in HTTP response header isn't mocked

### ISSUE THREAD

**Issue by KennethSundqvist** [hustcc/jest-date-mock#17]
This is a minor annoyance when I'm snapshotting the response headers. I'm currently working around this by using `{date: expect.any(String)}` in the snapshot property matchers.

No idea why this date isn't mocked, it is set by Node.js using `new Date()`:

https://github.com/nodejs/node/blob/f85b43537d6dff4004081fcc81f8aa771efbe1e5/lib/_http_outgoing.js#L321

https://github.com/nodejs/node/blob/f85b43537d6dff4004081fcc81f8aa771efbe1e5/lib/internal/http.js#L6-L14

**Comment by hustcc** [comment]
You should `advanceBy`, `advanceTo` at first, the the Date will return the mock timestamp.

**Comment by KennethSundqvist** [comment]
I have done so.

I created a small reproducible test case.

As you can see the `'Date'` snapshot has the mocked value but the `'Response headers'` doesn't.

**test.js**
```js
const dateMock = require('jest-date-mock')
const Koa = require('koa')
const supertest = require('supertest')

test('Mock date in headers', async () => {
  dateMock.advanceTo(new Date(2000, 0, 1))

  const app = new Koa()
  app.use((ctx) => {
    ctx.status = 200
  })

  const date = new Date().toUTCString()
  const res = await supertest(app.callback()).get('/')

  expect(date).toMatchSnapshot('Date')
  expect(res.headers).toMatchSnapshot('Response headers')
})
```

**test.js.snap**
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Mock date in headers: Date 1`] = `"Fri, 31 Dec 1999 23:00:00 GMT"`;

exports[`Mock date in headers: Response headers 1`] = `
Object {
  "connection": "close",
  "content-length": "2",
  "content-type": "text/plain; charset=utf-8",
  "date": "Fri, 23 Nov 2018 15:50:00 GMT",
}
`;
```

**Comment by hustcc** [comment]
try to set the jest env

```
/**
 * @jest-environment node
 */
```

at the beginning of test file. see testease in repo.

**Comment by jahusa02** [comment]
@KennethSundqvist 

Any chance you can remember how you fixed it?
