### ISSUE TITLE
It works without setupFiles config

### ISSUE THREAD

**Issue by klis87** [hustcc/jest-date-mock#18]
For some reason it works without putting
```js
{
  "jest": {
    "setupFiles": ["jest-date-mock"]
  }
}
```
in the config. 

Is it intended? For me `import { advanceBy, advanceTo, clear } from 'jest-date-mock'` is all I need in my tests.

**Comment by hustcc** [comment]
import it with setup config is the best way to use it.

or in your testease, import it in first line.

**Comment by klis87** [comment]
so u mean that putting it into config adds `import { advanceBy, advanceTo, clear } from 'jest-date-mock'` automatically to every test file? so to paraphrase it, it adds `advanceBy, advanceTo, clear` as global variables?

if that is so, I think it would be better to rename those, especially `clear`, as this name I guess is quite common and it could easily clash with local variables `clear`, I dont know, maybe `clearDateMocks` would be better?

**Comment by hustcc** [comment]
set in config, is not means global var.

you can understand the JavaScript module loading mechanism firstly.

**Comment by klis87** [comment]
I really dont understand. I know how module loading works in JS. I just refer to documentation where it is mentioned I should add this plugin to jest config, while it works perfectly fine without doing so. All I need is 
`import { advanceBy, advanceTo, clear } from 'jest-date-mock'` in files which mock `Date` object, no changes to jest config, and mocking works fine

**Comment by klis87** [comment]
@hustcc ok, thx, closing then
