### ISSUE TITLE
Breaks mongoose

### ISSUE THREAD

**Issue by andreialecu** [hustcc/jest-date-mock#21]
I've been running into hard to track issues with mongoose dates being saved as `Object` of `{ _id: ObjectId(...) }` instead of actual dates.

I've since found this: https://github.com/alexandr2110pro/jest-date-mock-mongoose-friendly

Not sure why the author didn't make it a PR or if there are any downsides to his approach, but just wanted to let leave this here for whoever might run into the same issue.

**Comment by hustcc** [comment]
Maybe you can help with a pr.

**Comment by andreialecu** [comment]
I found why this happens, it's because of this line in mongoose:

https://github.com/Automattic/mongoose/blob/6c6d74423263eec1442bb0777235cf3d64a1f28d/lib/schema.js#L963

Basically it needs the constructor function name to match the hardcoded `Date` schema type they use.

**Comment by andreialecu** [comment]
@hustcc you've got a PR

**Comment by epegzz** [comment]
@hustcc Could you please create a new release with this fix? :)

**Comment by hustcc** [comment]
v1.0.8 released. sorry for late.
