### ISSUE TITLE
Missing comparison section in README

### ISSUE THREAD

**Issue by luckylooke** [hustcc/jest-date-mock#27]
Hello 👋  

Could you please add section to README where you provide comparison to jest [Fake timers API](https://jestjs.io/docs/jest-object#fake-timers) ? 

Thanks 🙏

**Comment by hustcc** [comment]
One is `date` API, one is `timer`. Why need a section to compare them?

**Comment by luckylooke** [comment]
Both are operating with time and seems the same way.. so I wanted to know why should I use this library over official API 🤷 

jest-date-mock
```js
advanceTo(new Date(2018, 5, 27, 0, 0, 0)); // reset to date time.
```
seems to be same as https://jestjs.io/docs/jest-object#jestsetsystemtimenow-number--date

jest-date-mock
```js
advanceBy(3000); // advance time 3 seconds
```
seems to be same as https://jestjs.io/docs/jest-object#jestadvancetimersbytimemstorun

Thanks 🙏

**Comment by hustcc** [comment]
Date and timer is not same.

- `Date` is for calendar
- `timer` is for setTimeout or setInterval
