### ISSUE TITLE
Cannot assign to read only property 'now' of object 

### ISSUE THREAD

**Issue by Nikoms** [hustcc/jest-date-mock#31]
Hey!

I just updated to 1.0.9 (from 1.0.8) and tests are failing with this error when I try to import the library:
```
    TypeError: Cannot assign to read only property 'now' of object '[object EventTarget]'
```

It's failing with node `v18.20.0` but **it's working** in `v20.12.0`

**Comment by alopix** [comment]
We are observing the same issue for the new performance mock in Node for this line being called in the library:
```js
  // node / native env
  // …
  require('perf_hooks').performance.now
```

**Comment by hustcc** [comment]
Can help with a pr to fix it by remove the line.

**Comment by Nikoms** [comment]
Yes, I think it's the right way to do

**Comment by hustcc** [comment]
v1.0.10 released.
