### ISSUE TITLE
Mock Date class is not extensible

### ISSUE THREAD

**Issue by rubennorte** [hustcc/jest-date-mock#6]
The mock date class is returning a `Date` instance [in the constructor](https://github.com/hustcc/jest-date-mock/blob/master/src/mockDate.js#L12) which breaks extensibility (as an instance of `Date` is returned instead of the one of the class being used to call `new`).

As this is replacing the global `Date` object, any class extending `Date` would be broken.

**Comment by rubennorte** [comment]
Sure: https://github.com/hustcc/jest-date-mock/pull/7 ;)

**Comment by hustcc** [comment]
Thank you.

**Comment by rubennorte** [comment]
No problem. I see that you just bumped a new version but I don't see it published on npm. Can you please check? Thanks!

**Comment by hustcc** [comment]
done. ^_^

**Comment by prymitive** [comment]
I *think* (given that my tests started failing) that this made it impossible to pass `Date` to `advanceTo` as the README suggests, eg:
```
  advanceTo(new Date(2018, 5, 27, 0, 0, 0)); // reset to date time.
```
Since `Date()` always returns zero
Passing an integer with seconds since epoch seems to work

**Comment by rubennorte** [comment]
My bad. I created #8 with the fix. @hustcc please merge and release when you consider.

**Comment by hustcc** [comment]
Not your responsibility, but test cases are not perfect.

new beta version released, and 1.0.4 unpublished.

**Comment by prymitive** [comment]
I can confirm that 1.0.5-beta.1 works for me, should I expect 1.0.5 soon?

**Comment by hustcc** [comment]
@prymitive done.
