### ISSUE TITLE
1.0.4 broke tests

### ISSUE THREAD

**Issue by Jason-Abbott** [hustcc/jest-date-mock#9]
We have a `setup-jest.js` with these lines
```js
import { advanceTo } from 'jest-date-mock';
// all tests will run as if it's August (zero-based) 2018
advanceTo(new Date(2018, 7, 15, 0, 0, 0));
```
which had been working great but after 1.0.4 slipped in, a `new Date()` is returning timestamp 0, or 1/1/1970. We had to revert to 1.0.3 to fix our tests.

**Comment by hustcc** [comment]
+ jest-date-mock@1.0.5-beta.1
- jest-date-mock@1.0.4

release new version 1.0.5-beta.1, and unpublish version 1.0.4
